/run/initialize

/Pgun/Angle 0
/Pgun/Z -50 cm
/gun/energy 80 keV


/det/Angle 270
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 271
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 272
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 273
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 274
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 275
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 276
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 277
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 278
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 279
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 280
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 281
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 282
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 283
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 284
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 285
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 286
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 287
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 288
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 289
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 290
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 291
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 292
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 293
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 294
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 295
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 296
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 297
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 298
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 299
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 300
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 301
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 302
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 303
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 304
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 305
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 306
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 307
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 308
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 309
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 310
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 311
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 312
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 313
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 314
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 315
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 316
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 317
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 318
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 319
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 320
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 321
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 322
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 323
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 324
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 325
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 326
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 327
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 328
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 329
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 330
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 331
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 332
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 333
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 334
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 335
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 336
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 337
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 338
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 339
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 340
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 341
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 342
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 343
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 344
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 345
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 346
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 347
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 348
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 349
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 350
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 351
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 352
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 353
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 354
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 355
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 356
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 357
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 358
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 359
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 360
/run/reinitializeGeometry
/run/beamOn 10000000
