/run/initialize

/Pgun/Angle 0
/Pgun/Z -50 cm
/gun/energy 80 keV


/det/Angle 180
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 181
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 182
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 183
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 184
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 185
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 186
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 187
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 188
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 189
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 190
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 191
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 192
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 193
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 194
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 195
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 196
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 197
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 198
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 199
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 200
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 201
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 202
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 203
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 204
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 205
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 206
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 207
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 208
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 209
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 210
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 211
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 212
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 213
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 214
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 215
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 216
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 217
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 218
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 219
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 220
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 221
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 222
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 223
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 224
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 225
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 226
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 227
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 228
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 229
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 230
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 231
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 232
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 233
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 234
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 235
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 236
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 237
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 238
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 239
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 240
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 241
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 242
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 243
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 244
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 245
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 246
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 247
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 248
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 249
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 250
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 251
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 252
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 253
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 254
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 255
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 256
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 257
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 258
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 259
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 260
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 261
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 262
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 263
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 264
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 265
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 266
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 267
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 268
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 269
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 270
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 271
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 272
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 273
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 274
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 275
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 276
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 277
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 278
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 279
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 280
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 281
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 282
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 283
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 284
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 285
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 286
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 287
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 288
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 289
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 290
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 291
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 292
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 293
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 294
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 295
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 296
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 297
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 298
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 299
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 300
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 301
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 302
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 303
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 304
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 305
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 306
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 307
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 308
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 309
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 310
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 311
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 312
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 313
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 314
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 315
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 316
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 317
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 318
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 319
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 320
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 321
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 322
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 323
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 324
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 325
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 326
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 327
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 328
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 329
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 330
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 331
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 332
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 333
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 334
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 335
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 336
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 337
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 338
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 339
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 340
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 341
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 342
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 343
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 344
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 345
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 346
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 347
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 348
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 349
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 350
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 351
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 352
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 353
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 354
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 355
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 356
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 357
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 358
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 359
/run/reinitializeGeometry
/run/beamOn 10000000

/det/Angle 360
/run/reinitializeGeometry
/run/beamOn 10000000
