/run/initialize

/Pgun/Angle 0
/Pgun/Z -50 cm
/gun/energy 80 keV


/det/Angle 0
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 1
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 2
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 3
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 4
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 5
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 6
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 7
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 8
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 9
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 10
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 11
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 12
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 13
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 14
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 15
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 16
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 17
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 18
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 19
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 20
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 21
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 22
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 23
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 24
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 25
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 26
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 27
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 28
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 29
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 30
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 31
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 32
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 33
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 34
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 35
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 36
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 37
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 38
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 39
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 40
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 41
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 42
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 43
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 44
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 45
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 46
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 47
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 48
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 49
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 50
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 51
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 52
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 53
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 54
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 55
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 56
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 57
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 58
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 59
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 60
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 61
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 62
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 63
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 64
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 65
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 66
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 67
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 68
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 69
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 70
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 71
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 72
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 73
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 74
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 75
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 76
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 77
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 78
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 79
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 80
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 81
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 82
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 83
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 84
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 85
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 86
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 87
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 88
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 89
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 90
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 91
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 92
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 93
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 94
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 95
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 96
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 97
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 98
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 99
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 100
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 101
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 102
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 103
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 104
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 105
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 106
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 107
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 108
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 109
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 110
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 111
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 112
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 113
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 114
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 115
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 116
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 117
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 118
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 119
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 120
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 121
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 122
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 123
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 124
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 125
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 126
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 127
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 128
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 129
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 130
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 131
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 132
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 133
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 134
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 135
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 136
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 137
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 138
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 139
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 140
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 141
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 142
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 143
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 144
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 145
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 146
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 147
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 148
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 149
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 150
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 151
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 152
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 153
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 154
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 155
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 156
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 157
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 158
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 159
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 160
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 161
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 162
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 163
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 164
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 165
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 166
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 167
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 168
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 169
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 170
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 171
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 172
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 173
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 174
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 175
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 176
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 177
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 178
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 179
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 180
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 181
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 182
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 183
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 184
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 185
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 186
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 187
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 188
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 189
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 190
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 191
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 192
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 193
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 194
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 195
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 196
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 197
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 198
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 199
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 200
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 201
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 202
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 203
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 204
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 205
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 206
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 207
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 208
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 209
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 210
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 211
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 212
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 213
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 214
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 215
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 216
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 217
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 218
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 219
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 220
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 221
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 222
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 223
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 224
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 225
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 226
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 227
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 228
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 229
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 230
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 231
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 232
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 233
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 234
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 235
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 236
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 237
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 238
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 239
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 240
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 241
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 242
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 243
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 244
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 245
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 246
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 247
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 248
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 249
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 250
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 251
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 252
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 253
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 254
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 255
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 256
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 257
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 258
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 259
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 260
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 261
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 262
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 263
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 264
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 265
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 266
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 267
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 268
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 269
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 270
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 271
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 272
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 273
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 274
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 275
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 276
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 277
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 278
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 279
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 280
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 281
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 282
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 283
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 284
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 285
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 286
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 287
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 288
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 289
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 290
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 291
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 292
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 293
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 294
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 295
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 296
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 297
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 298
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 299
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 300
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 301
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 302
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 303
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 304
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 305
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 306
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 307
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 308
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 309
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 310
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 311
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 312
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 313
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 314
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 315
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 316
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 317
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 318
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 319
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 320
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 321
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 322
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 323
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 324
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 325
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 326
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 327
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 328
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 329
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 330
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 331
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 332
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 333
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 334
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 335
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 336
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 337
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 338
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 339
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 340
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 341
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 342
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 343
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 344
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 345
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 346
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 347
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 348
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 349
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 350
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 351
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 352
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 353
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 354
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 355
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 356
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 357
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 358
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 359
/run/reinitializeGeometry
/run/beamOn 1000000

/det/Angle 360
/run/reinitializeGeometry
/run/beamOn 1000000

# MANO DOBLE

/det/Angle 0
/run/reinitializeGeometry

/run/beamOn 100000000

/gun/energy 40 keV

/run/beamOn 100000000

